apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  #namespace: infrastructure
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiNDMxNDUzYWRkOGRlY2E2N2E0OGE3YzkzYTc1NGY3OTgiLCJ0IjoiOWQyMzBmMzQtMTc1NC00ZGE3LTgwMjItODE2N2QxYWFkMjZiIiwicyI6Ik5XVmxaV0l4Tm1JdFpUTmtZUzAwWXpFMkxUZzVNV1F0TnpRMlpEZG1NakZoT1RKbCJ9"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  #namespace: infrastructure
data:
  config.yaml: |
    metrics: 0.0.0.0:2000
    ingress:
    - hostname: lablocal.dpdns.org
      service: http://apivoltz.default.svc.cluster.local:3001
    - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  #namespace: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: TUNNEL_TOKEN
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared-config